name 'purplehazech-activerecord'
version '0.1.0'

author ''
license 'AGPL'
project_page 'https://github.com/purplehazech/puppet-activerecord'
source 'https://github.com/purplehazech/puppet-activerecord.git'
summary 'activerecord module'
description ''
dependency 'puppetlabs/stdlib', '>=3.2.0'
